version: '3.8'
services:
  icap-listener:
    image: ghcr.io/skyhighsecurity/gamsk8s/icap-listener:latest
    build:
      context: ./containers/icap-listener
      dockerfile: Dockerfile
    ports:
      - "1344:1344"
    environment:
      - MANAGER_SERVICE_URL=http://gam-manager:8000
    networks:
      - gam-network

  gam-manager-service:
    image: ghcr.io/skyhighsecurity/gamsk8s/gam-manager:latest
    container_name: gam-manager
    restart: always
    ports:
      - "5000:5000"
    environment:
      - GAM_HOST=gam-worker-service
      - GAM_PORT=8080
      - GAM_USER=testing
      - GAM_PASSWORD=testing
      - GAM_MALWARE_THRESHOLD=60
      - EXTRACT_PATH=/tmp/extracted_files
    volumes:
      - /tmp/extracted_files:/tmp/extracted_files
    networks:
      - gam-network

  gam-worker:
    image: ghcr.io/skyhighsecurity/gamsk8s/gam-worker:latest
    build:
      context: ./containers/gam-worker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AIRGAPPED="true"
      - APIUSERNAME="testing"
      - APIUSERPASSWORD="testing"
    volumes:
      - /path/to/license/gam-product.conf:/gam/gam-product.conf
      - /path/to/updates:/updates
    networks:
      - gam-network

networks:
  gam-network:
    driver: bridge

volumes:
  gam-updates:
    driver: local