apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gam-updates
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: oracle-fss #or other block storage that supports RWX, see OCI/oracle-fss.sc.yaml

